### ISSUE TITLE
ccREL XMP Python library (original #248)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-api#10]
This issue has been migrated from the [CC Search API repository](https://github.com/creativecommons/cccatalog-api/issues/248)

```
Author: aldenstpage
Date: Tue Mar 19 2019
Labels: ✨ goal: improvement,🏷 status: label work required,🙅 status: discontinued
```
A number of years ago, CC worked with W3C to create the Creative Commons Rights Expression Language (ccREL), which allows developers to embed metadata about licensing inside of webpages and files. To embed the metadata in files such as photographs or PDFs, the recommended approach is to use XMP (Extensible Metadata Platform), an XML based metadata language. This format is aging (although Adobe will soon be porting it to JSON-LD, which will make it much nicer to work with), and the tooling is difficult to use/sprasely documented. For these reasons and others, there is not that much ccREL data out in the wild. A Python library for embedding XMP into files may help lower the barrier for entry and increase the proliferation of licensing metadata.

CC Catalog API embeds this metadata through the `/watermark` endpoint. Once some non-trivial logic ends up in the `ccrel.py` controller, we should start thinking about splitting this into a separate dependency.

**Comment by sarayourfriend** [comment]
> To embed the metadata in files such as photographs or PDFs, the recommended approach is to use XMP (Extensible Metadata Platform), an XML based metadata language.

@aldenstpage Can you clarify what you meant here by "embed the metadata in files"? Would the XMP (or JSON-LD at this point, I suppose) be embedded in file metadata directly when it is proxied by Openverse or was there something else you had in mind? Would it be just embedding the JSON-LD for a result on the frontend (as produced by an API endpoint, maybe)?

**Comment by sarayourfriend** [comment]
@zackkrida I feel like this is something I've heard you talk about before. Do you have any ideas about how this issue is meant to be implemented, if it's something on the results themselves or something that would only be useful to put on the frontend side? Do we go fully into JSON-LD at this point? Would we do both?

**Comment by zackkrida** [comment]
@sarayourfriend I have discussed ccREL or adopting schema.org's [ImageObject](https://schema.org/ImageObject) json-ld schema for the purposes of allowing users to submit their works into Openverse. The general idea was:

1. Sites would include some kind of Openverse resource on their frontends, like an old-school 1x1px transparent image. This would act as a beacon to let our servers know that their page contains media for indexing in Openverse.
2. Our servers would visit their url and extract all schema.org ImageObject metadata (alonw with comparable metadata for other media types), which would provide all of the required fields for the Openverse catalog.
3. Also discussed: A WordPress plugin would be a great way to make this functionality available on a lot of sites. It could add metaboxes for licensing information in the user's media library; automatically generate and include the json-ld; and automatically embed the Openverse 'beacon' on any page which embeds these images from the media library.

I have not considered embedding metadata directly into media yet or its implications.

**Comment by sarayourfriend** [comment]
Gotcha, that makes a lot of sense.

I'm pretty confused by the intentions of this issue then. Do you have any insights into what it might mean, what a better title or description could be? Otherwise, I'd like to close it. Once we're working actively on a core integration/plugin that would implement open licensing to images on user-uploads to WP sites we can evaluate your suggestion, which _seems_ unrelated to the suggestion in this PR (which I admittedly do not understand).

**Comment by zackkrida** [comment]
I think the idea here is to create a utility for other platforms that would enable them to embed cc license information directly into media. I agree we can close it.
