### ISSUE TITLE
Update Postgres in ingestion server integration test

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#104]
Should be `13.2`

https://github.com/WordPress/openverse-api/blob/9d0d724651f18cc9f96931e01bea92b8032bd6a0/ingestion_server/test/integration-test-docker-compose.yml#L15

**Comment by krysal** [comment]
Note: This file is updated when running Ingestion server tests (instructions in README file, may require installing additional dependencies).

**Comment by zackkrida** [comment]
Ah yes, I learned this recently too, that this file is generated! I'm going to close this issue, thanks.
