### ISSUE TITLE
Remove resendverificationemails command and tests

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-api#1042]
## Problem

Now that verification emails are sent and the issue is fixed, we can remove this command. Critically, we can remove it's slow-running tests.

## Description

Remove the command and the associated tests. If we ever need it again for some reason we can revert the change.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sahil-R** [comment]
Hey @sarayourfriend, i see that this issue can be fixed by removing the test_auth_email_verification in the auth_test can I take this one as well??

**Comment by krysal** [comment]
It's yours @sahil-R!

**Comment by sahil-R** [comment]
Thank you, @krysal, @sarayourfriend, @AetherUnbound and @dhruvkb  How should I handle the cases when the api-test is done too frequently since the response that we get in that case is a 429? Should I assert for 429 or 200 or leave it as it is i.e. 200?

**Comment by sarayourfriend** [comment]
@sahil-R For this issue you should only need to delete the `resendverificationemails` command and the related tests. We shouldn't have to _change_ any tests, as far as I can think. Can you share a draft PR of what you've got going so far? It would be easier to advise if we could see the specific area you're mentioning.

> Also i have been waiting for the API to be healthy , when i do docker compose up i see that aiohttp module is not found however i have already installed it can you please also help me with this

You may need to run `just build web` to get the dependencies re-initialised in the Django base image. Any time dependencies change it requires rebuilding the web service's image.
