### ISSUE TITLE
Use `get_redis_connection` rather than `django.core.cache` for thumbnail timeouts

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#1073]
## Description

Capturing which domains had thumbnail timeouts on the API was added in #982. However, @sarayourfriend found that using `django.core.cache` implicitly uses the [default Django cache timeout](https://href.li/?https://docs.djangoproject.com/en/4.1/topics/cache/#cache-arguments). For our setup this is currently 5 minutes, which means that the thumbnail timeout entries only exist in Redis for 5 minutes.

We would like to switch the thumbnail timeout capturing from using the default `django.core.cache` to use `get_redis_connection` instead, so that no default timeout is applied when the associated values are added or updated.

## Additional context

This is a stop-gap change, and is intended to be supplanted by #1072

**Comment by sarayourfriend** [comment]
This was automatically resolved by the #1056 PR.
