### ISSUE TITLE
[Feature] Add image width and height to the API response

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-api#156]
## Problem

We have the information about image width and height in our database, however the API response does not include it.

## Description

Adding image width and height information will help the frontend rendering. 

## Alternatives

Currently, the size is calculated after the images are loaded, which adds unnecessary calculations and causes additional layout shifts. 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
`ImageSerializer` already has `height` and `width` both serialised as `IntergerField`s.

https://github.com/WordPress/openverse-api/blob/864ea3896a12cfdb39a3e6359ae897995daf97f4/openverse-api/catalog/api/serializers/image_serializers.py#L339

https://github.com/WordPress/openverse-api/blob/864ea3896a12cfdb39a3e6359ae897995daf97f4/openverse-api/catalog/api/serializers/image_serializers.py#L343

**Comment by obulat** [comment]
I'm closing this issue as the problem is in the underlying data not having width and height, not API not sending them.
