### ISSUE TITLE
/v1/thumbs should time out eventually (original #602)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-api#17]
This issue has been migrated from the [CC Search Frontend repository](https://github.com/creativecommons/cccatalog-api/issues/602)

```
Author: aldenstpage
Date: Wed Aug 26 2020
Labels: 💻 aspect: code,🙅 status: discontinued,🛠 goal: fix,🟨 priority: medium
```
## Description
If we are having a hard time loading a 3rd party image through our proxy, we should give up thumbnailing it. The frontend will fall back to the full sized image.

If we can't answer thumbnail requests quickly enough, our servers' workers become swamped with thumbnailing requests.

--------
### Original Comments: 

Issue author *tushar912* commented on Mon Sep 21 2020:

>@aldenstpage  I would like to work on this. Can u explain this issue a bit.
[source](https://github.com/creativecommons/cccatalog-api/issues/602#issuecomment-695955717)

*aldenstpage* commented on Wed Sep 23 2020:

>Hi @tushar912, I'd be happy to answer any specific questions you have about the ticket
[source](https://github.com/creativecommons/cccatalog-api/issues/602#issuecomment-697573929)

*manav1403* commented on Sun Oct 11 2020:

>@aldenstpage Is it correct that for this issue we have to set a timeout on request when full size is false and if the request exceeds timeout then send the response of the full-sized image
and what should be the value of the timeout?
[source](https://github.com/creativecommons/cccatalog-api/issues/602#issuecomment-706662657)

**Comment by zackkrida** [comment]
@WordPress/openverse we _have_ a timeout on this endpoint now, don't we?

**Comment by krysal** [comment]
Yes, we have it. Related to #630 and #756.
