### ISSUE TITLE
Cache top N searches (N=1,000,000?) in Redis (original #152)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-api#19]
This issue has been migrated from the [CC Search Frontend repository](https://github.com/creativecommons/cccatalog-api/issues/152)

```
Author: aldenstpage
Date: Wed Nov 28 2018
Labels: performance,✨ goal: improvement,🏷 status: label work required,🔒 staff only,🕹 aspect: interface,🙅 status: discontinued
```

--------
### Original Comments: 

*aldenstpage* commented on Wed Nov 28 2018:

>Assigned "low priority" because performance is adequate at current levels of traffic
[source](https://github.com/creativecommons/cccatalog-api/issues/152#issuecomment-442502828)

*muarachmann* commented on Mon Feb 24 2020:

>Hi @aldenstpage I would love to take on this. 
[source](https://github.com/creativecommons/cccatalog-api/issues/152#issuecomment-590516678)

*aldenstpage* commented on Fri Feb 28 2020:

>Hi @muarachmann, I suggest taking a look at a different issue. We don't have an immediate need for this performance improvement, and there are some nuances to this that may make it difficult for an external contributor to address.
[source](https://github.com/creativecommons/cccatalog-api/issues/152#issuecomment-592711180)

*muarachmann* commented on Thu Mar 05 2020:

>Hi @aldenstpage thanks for your reply, can you reference me to which issue i could easily pickup then :)
[source](https://github.com/creativecommons/cccatalog-api/issues/152#issuecomment-595231140)

**Comment by AetherUnbound** [comment]
I agree that this issue can be closed and a new issue on looking into the Cloudflare caching strategy would be a better investigation to prioritize 👍🏼
