### ISSUE TITLE
[Bug] Remove `.idea/dictionaries`

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#214]
We should stop tracking the `.idea/dictionaries` directory, as these are personal configuration files unsuitable for the repo.

**Comment by PuneetDabral** [comment]
sir can i do my first contribution here ?....but i need your support

**Comment by dhruvkb** [comment]
@PuneetDabral yes you can submit a PR fixing this issue. For issues labelled 'good first issue' you don't need to ask. Our [handbook](https://make.wordpress.org/openverse/handbook/new-contributor-guide/) might be a helpful read for you as a new contributor. You can also join us on [Slack](https://make.wordpress.org/chat/) (channel #openverse) or comment here if you need help with anything.

**Comment by PuneetDabral** [comment]
ok sir i should try it

**Comment by PuneetDabral** [comment]
sir i guess i need to move that directory to git ignore ...i am right?

**Comment by dhruvkb** [comment]
Yes, and delete the already checked-in directory as well.
