### ISSUE TITLE
[Bug] Directory naming consistiency

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#223]
We should rename the root `openverse-api` directory to `openverse_api` to match the naming convention of other root-level directories.

**Comment by MuhammadFaizanHaidar** [comment]
Hi @zackkrida  @dhruvkb I want to contribute to this ticket. I don't have access to rename root folder. I am a new contributor can I get some guide on this issue. I shall be grateful.

**Comment by obulat** [comment]
Hi @MuhammadFaizanHaidar , and thank you for your interest! 
You can fork this repository, make the change in your fork, and create a PR from there. GitHub has some documentation about forking: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks. Please feel free to ask us for help if you get stuck.

**Comment by MuhammadFaizanHaidar** [comment]
> Hi @MuhammadFaizanHaidar , and thank you for your interest!
> You can fork this repository, make the change in your fork, and create a PR from there. GitHub has some documentation about forking: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks. Please feel free to ask us for help if you get stuck.

@obulat thanks for quick response. I forked this repository and in my forked repository I updated root folder from openverse-api to openverse_api but I am not able to merge those changes to parent repository I think merges appear on changing files.
![openverse_api](https://user-images.githubusercontent.com/44171332/134345381-66bfd643-3424-4d19-940e-c3581910842f.PNG)

**Comment by obulat** [comment]
@MuhammadFaizanHaidar , I've looked at your repository fork, and I don't see a new branch there.
Here are the steps you can take to create a PR from your fork:
- create a branch for your change and check it out in git (you can use `git checkout -b name_of_your_branch` command in your terminal for that) 
- rename the root folder
- stage the changes to be committed(`git add .`)
- commit the changes (i.e. save them, by using `git commit -m "Text of your commit message"`)
- push your change to your github branch
- usually, when you open your fork (or pull requests tab of your fork) on github.com, you will see a message saying that changes have been pushed to your branch recently, and if you click on "Create PR" button, you will be able to create a PR.
GitHub also has a guide for creating PRs from your fork: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
I hope this helps you to figure it out
