### ISSUE TITLE
[Bug] Remove redundant `test/README`

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#261]
https://github.com/WordPress/openverse-api/blob/main/openverse_api/test/README doesn't have much information and is missing a `.md` extension. Therefore, we should remove it!

**Comment by dhruvkb** [comment]
Since the [`README.md` file for the API](https://github.com/WordPress/openverse-api/blob/main/openverse_api/README.md) has comprehensive steps for running tests (both on the host and within Docker) I recommend just getting rid of the file altogether.

**Comment by zackkrida** [comment]
Updated the ticket @dhruvkb
