### ISSUE TITLE
[Bug] Integration tests are failing due to audio thumbnails

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#274]
## Description

Currently the audio integration test suite is failing to due the `test_audio_thumb` test failing. I believe this is because there is wikimedia data in the https://github.com/WordPress/openverse-api/blob/29642df4dae2e2759f7f87c9d96e826ebe0eba28/sample_data/sample_audio_data.csv file and their audio files do not have thumbnail images.

## Reproduction
1. `just test` in the repo root

## Expectation

Tests to pass.

**Comment by dhruvkb** [comment]
The CI for `main` (at e8600d1) is passing.
