### ISSUE TITLE
Implement endpoint for processing bug reports from end users (original #264)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-api#35]
This issue has been migrated from the [CC Search API repository](https://github.com/creativecommons/cccatalog-api/issues/264)

```
Author: aldenstpage
Date: Wed Apr 10 2019
Labels: ✨ goal: improvement,🏷 status: label work required,🙅 status: discontinued
```
![Example request](https://i.imgur.com/QuXuklk.png)

Bugs should be forwarded to GitHub issues with a triage tag.

--------
### Original Comments: 

***Sando1* commented on Wed Oct 16 2019:**

>Hi @aldenstpage! I would like to work on this. 
[source](https://github.com/creativecommons/cccatalog-api/issues/264#issuecomment-542414242)

***DantrazTrev* commented on Tue Mar 03 2020:**

>Hi @aldenstpage is this still open for work
?

[source](https://github.com/creativecommons/cccatalog-api/issues/264#issuecomment-593916192)

***krysal* commented on Wed Apr 08 2020:**

>Hi @aldenstpage @annatuma 👋 Is this task different from [this](https://github.com/creativecommons/cccatalog-api/issues/474) other? If so I can work on this.
[source](https://github.com/creativecommons/cccatalog-api/issues/264#issuecomment-610682599)

***SaurabhAgarwala* commented on Fri Apr 24 2020:**

>@aldenstpage I would like to work on this issue. Please assign it to me.
[source](https://github.com/creativecommons/cccatalog-api/issues/264#issuecomment-619184014)

***krysal* commented on Fri Apr 24 2020:**

>@SaurabhAgarwala CC Staff is no longer assigning people to issues, you can start right away if you want, I wanted to work on this but was wondering is the endpoint is indeed still needed.
[source](https://github.com/creativecommons/cccatalog-api/issues/264#issuecomment-619232548)

***SaurabhAgarwala* commented on Sat Apr 25 2020:**

>@krysal I think we are free to submit a PR without being assigned only for those issues marked `help wanted`. For others, I believe we need permission. 
Yeah, even I was wondering if this endpoint is still needed and hence asked for permission.
If this endpoint is still needed, since you asked before, so you can work on it alone or if you want we can work collaboratively as well.
[source](https://github.com/creativecommons/cccatalog-api/issues/264#issuecomment-619252089)

**Comment by sarayourfriend** [comment]
@WordPress/openverse-maintainers Do we want to implement this issue? It _could_ be nice to make it easy for people to submit a bug report without needing a GitHub account, but moderating them would be a task all on its own. My preference would be to just stick with the regular GitHub issue process and direct folks to the WordPress Make Slack channel if they require help or can't open the issue themselves. Any objections to closing this?

**Comment by dhruvkb** [comment]
@sarayourfriend it seems reasonable to not implement this. We can focus our efforts on making our existing channels easier to use.

**Comment by dhruvkb** [comment]
@sarayourfriend it seems reasonable to not implement this. We can focus our efforts on making our existing bug channels easier to use.

**Comment by dhruvkb** [comment]
@sarayourfriend it seems reasonable to not implement this. We can focus our efforts on making our existing bug channels easier to use.
