### ISSUE TITLE
`just` scripting for the Analytics server

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#389]
For parity with the other packages in the repository and to help contributors, the https://github.com/WordPress/openverse-api/tree/main/analytics server should have `just` scripts added similarly to the ingestion server and api itself.

**Comment by dhruvkb** [comment]
It's important to identify the important jobs performed on the analytics server that we'd want to define recipes for.

- [x] testing (`just nl-test`)

**Comment by zackkrida** [comment]
Closing this, any new scripts needed can have standalone issues. We have an analytics server section in the Justfile now:

https://github.com/WordPress/openverse-api/blob/main/justfile#L188-L197
