### ISSUE TITLE
Analytics server is broken in production

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#390]
The analytics server is presently not working. In production, the analytics server's endpoints are added to the API domain. Here's some example nginx configuration to give you a sense of what I mean:

```nginx
# These endpoints point to the django api
location ~ ^/(v1|admin)/ {
      uwsgi_pass          django;
      # ...
  }

# /analytics points to the analytics server
location /analytics/ {
    proxy_pass http://
    # ...
}
```

If I recall correctly, the analytics server _should_ return documentation on the root, and currently we just have an error:

https://api.openverse.engineering/analytics/

We need to determine if these issues are the result of code errors, or production (mis)configuration.

**Comment by zackkrida** [comment]
Fixed via #442

**Comment by AetherUnbound** [comment]
Well, not quite :sweat_smile: I think it might be a good idea to leave this open until we get #484 merged as well. Until we do that, the analytics server is disabled in prod I believe since it has nowhere to store the data.

**Comment by AetherUnbound** [comment]
Err, I guess the issue specified in this ticket has been resolved - my bad!
