### ISSUE TITLE
Lint YAML files

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-api#410]
It seems that YAML files are not being linted and auto-fixed by `pre-commit`. This functionality should be added.

- `pre-commit` should lint and auto-format YAML files
- Lint check should also check PRs for the same rule

For example, consider this one-off 4-space indentation in a file that is otherwise indented by 2 spaces.
https://github.com/WordPress/openverse-api/blob/e2c490ad9d0f6ca47e5e2f4fd06205b7eac13c45/docker-compose.yml#L60
Pre commit should have fixed it and, if not, the linting check should have caught it.

**Comment by AetherUnbound** [comment]
I am....so sorry for that :sweat_smile: I need to figure out how to set per-file indentation on PyCharm :woman_facepalming:

Either way, love the idea of linting these!

**Comment by dhruvkb** [comment]
It's perfectly understandable to miss a couple of spaces, especially in YAML with all the hyphen-indents and what-not. Which makes linting them all the more necessary 👍.
