### ISSUE TITLE
Send crawled images to be processed by AWS Rekognition (original #584)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-api#42]
This issue has been migrated from the [CC Search Frontend repository](https://github.com/creativecommons/cccatalog-api/issues/584)

```
Author: kgodey
Date: Fri Aug 07 2020
Labels: 🏷 status: label work required,🔒 staff only,🙅 status: discontinued
```
We have a feed of image metadata coming in from our crawler. We want to feed the 77MM images we've deemed worth crawling to Rekognition.

Use a Kafka topic to direct EC2 worker instance(s) to feed images to Rekognition. We should store the full response from Rekognition, including any bounding boxes, in a topic named `rekognition_results`.

**We can't start feeding images to Rekognition until we have opted out of [Amazon's AI services](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_ai-opt-out.html)**.

- [x] Opted out of AI services
--------
### Original Comments: 

*aldenstpage* commented on Wed Aug 19 2020:

>I've opted us out of AI services for all regions using the [organization policy console](https://console.aws.amazon.com/organizations/home).
[source](https://github.com/creativecommons/cccatalog-api/issues/584#issuecomment-676689719)

*aldenstpage* commented on Mon Aug 31 2020:

>We're having conversations with AWS about architecture and cost minimization, so I'm marking this as blocked for the time being.
[source](https://github.com/creativecommons/cccatalog-api/issues/584#issuecomment-683912056)

*aldenstpage* commented on Tue Sep 22 2020:

>This is blocked while we wait for a deal with AWS to be finalized
[source](https://github.com/creativecommons/cccatalog-api/issues/584#issuecomment-696778956)

**Comment by sarayourfriend** [comment]
@WordPress/openverse-maintainers This issue seems like it could be closed. The suggested approach doesn't make sense unless we've already agreed to use the Rekognition data we already have from the grant. We've got a project potentially listed for 2023 to decide whether we can and how to use that data. Can we close this issue in the meantime?

**Comment by AetherUnbound** [comment]
I agree we can close this issue, I'll go ahead and do so.

**Comment by zackkrida** [comment]
For context, this issue actually _was_ completed at the time. This issue describes the initial push to collect rekognition data on a subset of the Openverse catalog. We're in possession of this data.
