### ISSUE TITLE
Remove supervisord in ingestion server image

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#425]
## Problem

Currently the ingestion server installs `supervisord` and uses it to run the integration server. Ostensibly, it looks like this was done in order to restart the ingestion server if it fell over.

## Description

Service restarts should be the purview of the Docker supervisor (e.g. docker-compose in this case) and should not be managed within the container. Additionally, the Docker command is always run with PID 1. Replacing this with `supervisord` means that any signals which get sent to the Docker container (and thus `supervisord`) may not be properly propagated to the webserver process.

As part of this, we should also set the relevant docker-compose files to restart the container automatically.

## Additional context

This appears to be the only context I can find for adding `supervisord`:
https://github.com/creativecommons/cccatalog-api/commit/4a13a40a7e4c94fea0a097799b6ded9db12315c3

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
It does make sense to remove the `supervisord` layer and just run `gunicorn` directly on the container itself. This would also be a good time to ensure parity in the services that all three containers use to host their HTTP APIs.
