### ISSUE TITLE
Replace `publish_release.sh` with a Just recipe

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-api#441]
## Problem

The script `ingestion_server/publish_release.sh` performs one, quite simple task. It should not live on as a standalone, undocumented script.

## Description

 It can be
- changed into a Just recipe
- generalised to also build and tag images for other services

## Alternatives

In the bigger picture, it can be integrated into our CI + CD workflow (see PRs #424 and #437) or be completely replaced by it and deleted.

## Additional context

Such undocumented scripts are detrimental to DX as people can forget why they exist.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by PrabhavPandey** [comment]
Hey, @dhruvkb. I would like to fix this issue, but in all honesty, I have no idea how to start. Any pointers that might help?
This is my first try at open source😄

**Comment by dhruvkb** [comment]
@PrabhavPandey this ticket isn't ready for work yet (my mistake for the incorrect labelling). The PRs mentioned above need to be merged before this can be fixed.

Would you kindly pick an alternative ticket?

**Comment by dhruvkb** [comment]
@PrabhavPandey this ticket isn't ready for work yet (my mistake for the incorrect labelling). The PRs mentioned above need to be merged before this can be fixed.

Would you kindly pick an alternative ticket?

**Comment by PrabhavPandey** [comment]
Sure. Thank you!

**Comment by dhruvkb** [comment]
@PrabhavPandey the blocking PR has been merged, so you can go ahead and delete the file, including all references to it.

**Comment by PrabhavPandey** [comment]
@dhruvkb I have opened a pull request for the task assigned
