### ISSUE TITLE
Use `::` over `cast` in audioset_view

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#467]
## Problem

We have a few different forms of the `audioset_view` definition (see WordPress/openverse-catalog#320).

## Description

These should be unified so all definitions are the same, even if [`cast` and `::` serve the same purpose](https://www.postgresql.org/docs/13/sql-expressions.html#SQL-SYNTAX-TYPE-CASTS). That syntax also already exists in the [ingestion server mock schema DDL](https://github.com/WordPress/openverse-api/blob/a7aa53ffc5f9d3b8b6bebf9dbacba248623a5a61/ingestion_server/test/mock_schemas/audioset_view.sql#L22), so we can apply that to the `load_sample_data.sh` script.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
It would be ideal if the mock schemas from `ingestion_server/test/` could directly be used inside the `load_sample_data.sh` script as that would prevent the need to maintain two copies of the same SQL in the same repo.

**Comment by pkthinklp** [comment]
Hello, I'm new to open source and I would like to give this a try!
could you please anyone give me more context on this issue?
Thank you.

**Comment by AetherUnbound** [comment]
Hi @pkthinklp! We'd love to have you help out with this issue. We'd like to change all of the `cast(x ... as y)` calls in the following location to `x::y` instead: 

https://github.com/WordPress/openverse-api/blob/392980106b2cf9444b877c27b1cf32af09d053c6/load_sample_data.sh#L83-L91

Let us know if you'd like to take that on!

**Comment by parthpatel9414** [comment]
Hello @AetherUnbound, First of all
Thank you so much for explaining the issue very briefly.
 I will be contributing from @parthpatel9414 account as the old one belongs to work. 
 Thank you.
