### ISSUE TITLE
Add "limited reporting" mode for ingestion server

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#481]
## Problem

When running a data refresh in dev, we really don't need to have the same level of granularity for slack alerts that we do in production. We mostly just need "starting" and "done".

## Description

It would be great to have a simple way of distinguishing that some messages should only be sent in prod.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Something resembling log levels in our slack alerting utility would be a clean way to approach this.

**Comment by AetherUnbound** [comment]
This relates to milestone 1.2.0 in the catalog repo: https://github.com/WordPress/openverse-catalog/milestone/2
