### ISSUE TITLE
Analytics data should be in a separate database

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#484]
## Problem

Analytics data is currently being stored in the same database as the API. While the API and the analytics server use different migration tools (Django vs alembic respectively), there could still be opportunities for migration conflicts.

## Description

For data integrity purposes these should exist in completely separate databases.

## Alternatives

Determine whether we need the analytics server and/or investigate another monitoring/metrics system.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
This relates to milestone 1.4.0 in the catalog repo: https://github.com/WordPress/openverse-catalog/milestone/4

**Comment by sarayourfriend** [comment]
Closing this as the analytics service no longer exists.
