### ISSUE TITLE
Version number is confusing

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#485]
## Description

The version number of the API is prepended with some confusing additional text in the documentation `3387VERSION+`:

![CleanShot 2022-01-24 at 19 35 25@2x](https://user-images.githubusercontent.com/6351754/150888576-60182d8f-7efe-4dcf-8027-4e746345b46d.png)

## Reproduction

1. Visit https://api.openverse.engineering/v1
2. Observe text `3387VERSION+` at the start of the version number

## Environment

 - Device: 
 - OS: 
 - Browser: 
 - Version: 
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
This looks to be due to the way we're setting the `SEMANTIC_VERSION` variable on deployment. Should we move this over to the infra repo?

**Comment by dhruvkb** [comment]
Moved to Automattic/openverse-infrastructure#80
