### ISSUE TITLE
Reference quickstart guide in top level README.md

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#488]
## Description

The top-level README does not provide any information or references for running the stack. That information was moved out into a separate docs file in #427. It might be beneficial for first-time contributors to reference that document from the top-level README, since they may not know where to look for it.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
True, the `README.md` should reference both the API consumer docs at https://api.openverse.engineering/, and the API developer docs at https://wordpress.github.io/openverse-api.
