### ISSUE TITLE
Cache waveform data

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-api#490]
## Problem

Fetching waveform data from the API currently generates the waveform on every hit.

## Description

This should be cached to only be calculated the first time the waveform for an audio is requested.

We can use any caching strategy we want, but it'll have to be cached on disk rather than memory (I would think) to avoid filling up RAM and forcing the main application processes to use swap. Could we just cache it directly in the DB?

Django supports many caching strategies that allow using the Django provided `cache` object: https://docs.djangoproject.com/en/4.0/topics/cache/

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
We're actually already using a cache for a few other things in the API! https://github.com/WordPress/openverse-api/blob/main/api/catalog/settings.py#L154

It should be fairly straightforward to add the waveforms to that cache as well.
