### ISSUE TITLE
Turn down Sentry transaction sample rate

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-api#502]
## Problem

We're far exceeding Sentry's transaction monitoring limits because our sample size is 100% and we're not even using it. This is making Sentry's UI mad at us.

## Description

Let's turn off transaction sampling altogether by setting the traces sample rate to `0`.

## Additional context

If we don't do this eventually Sentry will start dropping errors and no longer alerting us of new issues.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
What does the sample rate/size accomplish?

**Comment by sarayourfriend** [comment]
It corresponds to the percentage of requests that get traced by Sentry for performance: https://docs.sentry.io/platforms/python/guides/django/performance/

https://docs.sentry.io/product/sentry-basics/tracing/distributed-tracing/

More info here: https://docs.sentry.io/platforms/python/guides/django/performance/#verify

We don't use Sentry for performance monitoring. We'll use Prometheus for that once we've got it set up, so there's no sense in exhausting Sentry's general limits on our account for errors with transactions that we don't care about monitoring right now anyway.

**Comment by AetherUnbound** [comment]
Thanks for that info! It seems like we might also be able to add Sentry to [Airflow](https://docs.sentry.io/platforms/python/guides/airflow/), which could be useful for the catalog!

**Comment by AetherUnbound** [comment]
It turns out that, [thanks to this env var](https://github.com/WordPress/openverse-api/blob/ab26c741d660707da9647d406e706759c70c5a82/api/catalog/settings.py#L313), we don't even have to make a code change! I can deploy a new version with this turned off now.

**Comment by AetherUnbound** [comment]
Fixed with a new deployment which disables Sentry transaction sampling.
