### ISSUE TITLE
No verification email received / 502 from registration endpoint

### ISSUE THREAD

**Issue by dmathewwws** [WordPress/openverse-api#506]
## Description
I registered my app got back a successful message that includes "check your email for a verification link". I never got an email to verify my app and increase my rate limits.

## Reproduction
1) Register App via the 'https://api.openverse.engineering/v1/auth_tokens/register' endpoint.
2) Get back successful response, with client_id, client_secret, and msg that says "Check your email for a verification link"
3) No Email received, waited 10 hours (to make sure), checked my spam folder.

## Expectation
Get an email to verify my email.

**Comment by zackkrida** [comment]
Thank you for reporting @DantrazTrev this is a know issue and we will deploy our fix tomorrow! Feel free to email openverse@wordpress.org for specifics regarding verifying your API account's API access.

**Comment by sarayourfriend** [comment]
@zackkrida Is this fixed? I tried to register for a token today using the following request and got a 502 from cloudflare and no email:

```
curl \
  -X POST \
  -H "Content-Type: application/json" \
  -d '{"name": "Testing current auth flow", "description": "@sarayourfriend testing", "email": "guardian.flag2708@fastmail.com"}' \
  "https://api.openverse.engineering/v1/auth_tokens/register"
```

However, I believe the token is actually created as when I make the request again, I get back this response:

```
{"name":["o auth2 registration with this name already exists."]}                                   
```

No email though :cry:

**Comment by AetherUnbound** [comment]
I believe this is still an issue, related to: https://github.com/WordPress/openverse-infrastructure/issues/52

**Comment by zackkrida** [comment]
As discussed elsewhere this is _still_ an issue, but with an upcoming fix. Thanks @sarayourfriend and @AetherUnbound for your ongoing efforts to fix this.

**Comment by sarayourfriend** [comment]
@dmathewwws This issue is resolved. Feel free to request another token, you should receive an email as expected now. Otherwise, we're in the process of finding a way to get people access to the tokens they originally requested and you'll hear from us eventually about that.
