### ISSUE TITLE
Remove `pipdeptree`

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#516]
## Problem

`pipdeptree` is specified as a dependency but we are no longer using it now that we are using Pipenv.

It's only explicitly defined in the ingestion server here: https://github.com/WordPress/openverse-api/blob/f81cd0b3176cca46b8acdbfe288a69bf865f3dd9/ingestion_server/Pipfile#L9

## Description

Remove `pipdeptree`.

## Additional context

See #497, #231

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
Someone has reached out to me wanting to help with this ticket - they'll comment here soon!

**Comment by GowthamChowdary** [comment]
willing to take it up if it's still open

**Comment by dhruvkb** [comment]
@AetherUnbound is @GowthamChowdary the one who had reached out to you?

**Comment by AetherUnbound** [comment]
It was @AveryM15, but we can find another issue for them - @GowthamChowdary if you would like it, it's yours!

**Comment by GowthamChowdary** [comment]
Thanks @AetherUnbound  , i'd love to work on this !
