### ISSUE TITLE
Audio waveform cache-warming Django command

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#529]
## Description

Related to #510

We now have a table where audio waveforms are cached, but this table is not yet fully populated. We have plans to move this processing upstream into the catalog (https://github.com/WordPress/openverse-catalog/issues/363). 

For the time being, we should create a Django command that can be run with `python manage.py <command>` which will iterate through all audio records and generate waveforms for them. Here is an outline of the necessary code:

```python
audios = Audio.objects.all()
with tqdm(total=audios.count()) as progress:
    for audio in audios:
        audio.get_or_create_waveform()
        progress.update(1)
```

The above code example uses `tqdm`, which I don't believe is a dependency we have right now. We could add it for this use and remove it after, since the progress bar and estimated time to completion are very useful. 

We have ~14k records, and a test run on staging showed that this could take anywhere from 12-48 hours.
![image (3)](https://user-images.githubusercontent.com/10214785/155229823-8f7a846f-11ff-4c32-8898-b6407f5aa0f6.png)

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
It might be good to order the audio objects by `id`, so that the results are reproducible on multiple runs.

**Comment by zackkrida** [comment]
> 12-48 hours

That's quite a long time, and makes me wonder if handling this during the data refresh or in the catalog is even a good idea. Assuming the number of audio records _never_ increased from the current numbers, this would still _dramatically_ increase the data refresh time, right?

**Comment by AetherUnbound** [comment]
It would, seeing as audio currently takes about 5 minutes. However, we would only need to go through the initial records _once_; after the waveform for those have been generated, they can be skipped and only new audio records will require waveform generation.
