### ISSUE TITLE
Upgrade to Django 4

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-api#549]
## Problem

Django 4 is released and we can upgrade to it.

## Description

As with most Django major version upgrades, there are some breaking changes

https://docs.djangoproject.com/en/4.0/releases/4.0/#backwards-incompatible-changes-in-4-0

We need to go through this list and ensure that we're not effected by them or update the places that are. If there's significant work to get ready for Django 4 upgrade then open other issues to address them in small testable PRs.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
I've [approved](https://github.com/WordPress/openverse-api/pull/548#issuecomment-1059906253) Dependabot's PR to upgrade to Django 4.0.3.

**Comment by krysal** [comment]
It's done in #548.
