### ISSUE TITLE
Query param to exclude a source

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#553]
## Problem

As the number of sources in Openverse grows, it may prove beneficial to API users and the frontend to be able to _exclude_ sources, as opposed to limiting results by a list of included sources.

A primary use case I see for this is to omit Flickr, if one doesn't want to see content that can vary greatly in quality, as opposed to the other, more consistent platforms.

**Comment by sarayourfriend** [comment]
I'm curious about learning how our ES integration works so I'd like to poke around on this one if that's okay!

**Comment by dhruvkb** [comment]
@sarayourfriend I'm so sorry I didn't see your comment here! Feel free to push your work on top of this PR or make a new one so that we can compare approaches.
