### ISSUE TITLE
Define categories as constants

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-api#558]
## Problem

For both audio and images, categories are defined as strings in the serializer.

image:
https://github.com/WordPress/openverse-api/blob/88ca7f7172fe2b286091cb6a83a759d2e727d692/api/catalog/api/serializers/image_serializers.py#L37

audio:
https://github.com/WordPress/openverse-api/blob/88ca7f7172fe2b286091cb6a83a759d2e727d692/api/catalog/api/serializers/audio_serializers.py#L61

## Description

These categories should me moved into a constants module for 
- better understanding of available categories
- easier modifications in the future

Relates to #526.

**Comment by ritikBhandari** [comment]
Hi @dhruvkb, can I work on this issue?

**Comment by dhruvkb** [comment]
@ritikBhandari sure, please do.

**Comment by ritikBhandari** [comment]
So to make it clear, 
What we have to do is move these categories into separate modules and import them for their current usage. Right?

**Comment by dhruvkb** [comment]
Yes, we have a `constants/` package in `api/catalog/api/` where you can make a new module like `categories.py` and define the categories there like [Django `choice` classes](https://docs.djangoproject.com/en/4.0/ref/models/fields/#enumeration-types). 

Then we can use [DRF `ChoiceField`](https://www.django-rest-framework.org/api-guide/fields/#choicefield) to automatically perform the validation on the API.
