### ISSUE TITLE
Create an unrestricted rate limit model

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#565]
## Problem

For Openverse integrations with large platforms or trusted partners, we need an unlimited rate limit model added.

## Description

> current rate limit groups
<img width="316" alt="CleanShot 2022-03-11 at 16 07 18@2x" src="https://user-images.githubusercontent.com/6351754/157966746-722c0bf3-cb22-4040-9e98-32738f32cd0f.png">

https://github.com/WordPress/openverse-api/blob/ab26c741d660707da9647d406e706759c70c5a82/api/catalog/settings.py#L128

Openverse uses the throttling functionality from [django rest framework](https://www.django-rest-framework.org/api-guide/throttling/). It seems we either need to create a class with extremely high limits, or add a way for throttled applications to be _exempted_ from throttling entirely.

**Comment by dhruvkb** [comment]
DRF allows [turning throttling off](https://www.django-rest-framework.org/api-guide/throttling/#setting-the-throttling-policy) on endpoints by setting the throttling classes to an empty list `[ ]` or empty tuple `(, )`.

**Comment by sarayourfriend** [comment]
@dhruvkb we only want to remove throttling for specific API keys though. I believe that'd require a separate throttle class, right? I think we still want throttling on all endpoints otherwise.

**Comment by dhruvkb** [comment]
Sorry I misunderstood the issue. Yeah, we'll need a new throttling class in that case.
