### ISSUE TITLE
Return secure URLs for the fields thumbnail, detail_url and related_url.

### ISSUE THREAD

**Issue by oskosk** [WordPress/openverse-api#573]
_(Framed the verbiage of the title as a feature request)_ 🙏 

## Problem

The response for search and detail requests includes insecure URLs (`http` instead of `https`) in the fields `thumbnail`, `detail_url` and `related_url`.

![image](https://user-images.githubusercontent.com/746152/158834288-6b49c399-3b8c-48c8-8529-cdff970686a3.png)

e.g.:

**Search**

https://api.openverse.engineering/v1/images/?q=flower

**Detail:**

https://api.openverse.engineering/v1/images/6c1769b0-a3e5-4dae-8a36-8531a6e1430f/

## Description

When trying to integrate Openverse with some code on the browser I ended up having to replace the scheme part of the URL for avoiding notices like ```xxxx was loaded over HTTPS, but requested an insecure resource 'http://api.openverse.engineering/v1/images/6c1769b0-a3e5-4dae-8a36-8531a6e1430f/'. This request has been blocked; the content must be served over HTTPS.`

**Comment by dhruvkb** [comment]
I think this [StackOverflow question](https://stackoverflow.com/questions/62047354/build-absolute-uri-with-https-behind-reverse-proxy) is the cause of the issue.

**Comment by AetherUnbound** [comment]
Unfortunately our two attempts to address this did not prove successful in production. Re-opening this issue.
