### ISSUE TITLE
Return `mature` status in the single result endpoints

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#587]
## Problem

Currently one is able to _search by_ mature/not mature images, but we don't have this status available in the single results.

## Description

Add a new item to the response for single images denoting if they are mature or not. This would allow us to, for example, blur the images on single results unless the user consents to viewing mature content.

## Additional context

This may require a db join / relationship query when we load the single image results direct from the DB, which could impact performance. 

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
Done in #936.
