### ISSUE TITLE
Publish a docker image on each (non draft) PR commit

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#597]
## Problem

We are currently only publishing tagged docker images to GHCR when a release is cut. When we are deploying, (currently only with the ingestion server/indexer workers, but ideally with the API down the road) we have the option to deploy a specific docker image tag. We can point the API to a specific commit and deploy said commit (in staging, for instance). We do not currently have an allegory for the docker images.

## Description

We should add logic to the CI/CD to push the docker image tagged with the commit **on every PR commit**. That way individual commits can be used for deployments rather than having to cut a release in order to test something in staging.

While this might seem like it would pollute GHCR with tons of images, the reality is that a new image would be pushed only if changes to the docker image have occurred! In most of our code-change cases, the produced docker image has the exact same hash as the one published before it. Example: https://github.com/wordpress/openverse-api/pkgs/container/openverse-api/17792291?tag=2b3d93521811ffd4554f3ad44db6b585401f41e2 _(Note the `Other tags on this version` section in the bottom right)_.

We should probably restrict this step to non-draft PRs; there's no sense in pushing a docker image on a PR that we know is still a work in progress.

## Additional context

For one possible implementation, see: 6abdcbdd523b154f37b393fb9a24e2e3cf9d0870

We may also want to do something similar for the catalog.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
A smaller problem would be that PRs from forks will not be able to access the GHCR using the token so we need to skip that step using an `if` check.

**Comment by AetherUnbound** [comment]
Ahh, that's a good point!

**Comment by dhruvkb** [comment]
I'll pile on some more troubles.

- A non-technical issue is that a lot of people might not strictly follow the draft PR for WIP / non-draft for ready rule. It can lead to some not-ready code getting built into images.
- PRs can be readily changed between draft and ready. Which means we might need to build images when marked ready and delete any built images when converted to draft.
- What happens in case of a force push? Would we delete the images in GHCR associated with dangling commits?

**Comment by AetherUnbound** [comment]
Oof, those are troublesome. It's possible that we could mitigate this by specifically setting `pull_request` rather than `pull_request_target`, so it only happens on PRs made by maintainers. This would make it hard to test non-maintainer PRs in the same manner though.

One alternative we could have: we don't _need_ to test a deployment of every PR on staging at this time. Perhaps we could have a workflow defined that would tag & push the images built from a particular branch? GitHub will let you kick off GHA runs on `workflow_dispatch` enabled workflows, and target a particular branch. Then we could manually trigger that process when needed, otherwise the images wouldn't be pushed by default.

**Comment by dhruvkb** [comment]
Ah, triggering this workflow via dispatch seems like a manual, but very reliable, solution. I still think it won't work for forks but it still covers the vast majority of cases (as of now) which are be PRs made by the maintainers themselves.
