### ISSUE TITLE
Add a check job in the CI+CD workflow

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-api#631]
## Problem

The CI+CD workflow should invoke [Django checks](https://docs.djangoproject.com/en/4.0/ref/checks/).

```bash
$ python manage.py check
```

## Description

The Django [check command](https://docs.djangoproject.com/en/4.0/ref/django-admin/#check) can catch a number of problems in the codebase and act as an effective way to identify possible bugs.

## Alternatives

This is just an addition, we already have some unit and integration tests to catch most major issues.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
TIL! This is would be a great addition!
