### ISSUE TITLE
Update h2non/bimg to v1.1.9 in imaginary

### ISSUE THREAD

**Issue by Dachande663** [WordPress/openverse-api#646]
Currently https://github.com/WordPress/openverse-api/blob/main/.github/workflows/build_imaginary.yml uses sed to swap the bimg version from 1.1.4 to 1.1.7 due to a bug in the official imaginary build preventing it from building.

V1.1.9 of bimg adds support for saving as GIF which is an oft-requested feature.

Looking at the changelogs, there shouldn't be any BC breaking changes.

**Comment by sarayourfriend** [comment]
@Dachande663 would you be interested in opening a PR for this? It seems like it'd just be a one-liner to swap the version number.

**Comment by Dachande663** [comment]
@sarayourfriend opened :) #647
