### ISSUE TITLE
Medium duration is unavailable

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#653]
## Description

We have a `medium` duration defined in Elasticsearch: 

https://github.com/WordPress/openverse-api/blob/a7955c86d43bff504e8d41454f68717d79dd3a44/ingestion_server/ingestion_server/elasticsearch_models.py#L308

This value is not specified in the list of valid durations, and will thus fail when used in a query: 

https://github.com/WordPress/openverse-api/blob/fbca822683f4b18a692ac34291d4642309946302/api/catalog/api/constants/field_values.py#L28-L31

## Reproduction

1. Visit https://api.openverse.engineering/v1/audio/?q=whale&duration=medium
2. Observe the following errror

```
HTTP 400 Bad Request
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": {
        "duration": [
            "Invalid duration: medium. Available options: {'short', 'long'}"
        ]
    }
}
```

## Additional context

Related to #652

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
Remarking this as critical as it breaks one of the unique audio filters. Despite audio being in beta, it still seems like this issue is pretty bad (and it's not blocking other work, it's just plain broken, so high doesn't seem to fit).
