### ISSUE TITLE
Registering an application leads to a 502 Bad Gateway 

### ISSUE THREAD

**Issue by mirko314** [WordPress/openverse-api#675]
## Description
Registering an application leads to a 502 Bad Gateway after a long wait. Instead of receiving my secret I got the following nginx error: 

```<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.12.2</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194" integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw==" data-cf-beacon='{"rayId":"705b60ed9e588fda","token":"b84c1fc0e0174d7bafb20aa9869dd416","version":"2021.12.0","si":100}' crossorigin="anonymous"></script>
</body>
</html> 
```

## Reproduction

1. Register a new application (change the name): `curl   -X POST   -H "Content-Type: application/json"   -d '{"name": "Test 123", "description": "To access Openverse API", "email": "email@test.com"}'   "https://api.openverse.engineering/v1/auth_tokens/register"`
2. see error

Executing it a second time leads to `{"name":["o auth2 registration with this name already exists."]}%` so it does seem to create a new account. But without the client secret, this account is unreachable.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
Thank you for submitting this issue @mirko314! This is related to #506 and we are hoping to address it this week. I'm going to close this in favor of the other issue, but please keep your eyes on it!
