### ISSUE TITLE
Rename `nsfw_reports` to `nsfw_reports_image`

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#719]
## Problem

We presently have the image report table named `nsfw_reports` and the same table for audio named `nsfw_reports_audio`. We should rename the former to `nsfw_reports_image` to make the tables consistent. This will also allow us to generate these tables with interpolation (vis-a-vis WordPress/openverse-catalog#513)

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sora-san45** [comment]
Could you specify the file locations where the change has to be made

**Comment by zackkrida** [comment]
While we're renaming these tables, we might want to switch the language to `sensitive_reports_images` and `sensitive_reports_audio` unless it requires more effort.

**Comment by AetherUnbound** [comment]
In order to make this change part of a zero-downtime deployment, we'd need to take the approach outlined in #1082. The alternative would be to change the models so internal references use the name @zackkrida suggested while referencing the same underlying table (see [`db_table` documentation](https://docs.djangoproject.com/en/4.1/ref/models/options/#django.db.models.Options.db_table)). Technically we're already doing that, since the model itself is just called `ImageReport`:

https://github.com/WordPress/openverse-api/blob/5745fb76bacd3c2b49d43cbb0f00b96fbe8313c6/api/catalog/api/models/image.py#L106

With all that in mind, I'm going to go ahead and close this issue since it's 1) superficial and 2) would require a downtime deployment or a large amount of work to perform in a zero-downtime fashion.
