### ISSUE TITLE
License validation does not work correctly for non-lower-case strings

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-api#740]
## Description

When filtering a search by `license`, and use a non-lower-cased license, you don't receive an error message, but you also don't get any results.

## Reproduction

1. Search for images with an uppercase license filter: http://localhost:8000/v1/images/?q=cat&license=BY-SA
2. See error: You'll get no results, and no errors. If you use an invalid license string, then you'd get an error:
```
{
    "detail": {
        "license": [
            "License 'by-sta' does not exist."
        ]
    }
}
```
## Additional context

I'm not sure what the best solution here would be:
- consider any case of license valid if it's a valid license when lowercased(`license=BY-sa` returns all items with `by-sa` license)
- consider the licenses invalid if they have incorrect case (`license=BY` throws an error)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by raghuvar-arora-au2** [comment]
Can I work on this, please? I believe it makes more sense to not keep it case-sensitive

**Comment by sarayourfriend** [comment]
Sure thing! However, it looks like you also have this issue still assigned to you: https://github.com/WordPress/openverse-api/issues/758

Are you still planning on working on that one?

**Comment by raghuvar-arora-au2** [comment]
yeah. I'll get it done by tomorrow if that's okay

**Comment by sarayourfriend** [comment]
Oh, there's no rush! Just wanted to make sure I understood your intentions. Thanks!
