### ISSUE TITLE
Limit unauthenticated API requests to 20 page size

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-api#751]
## Problem

Currently it's possible to send page_size up to 500. This makes it trivial for someone to DDoS the API, even if they're getting throttled.

Note: I'm marking this high instead of critical because we can't deploy the API right now anyway to fix it (although maybe this would help prevent the API issues we were seeing, something to investigate).

## Description

Limit the page_size to 20 for requests without authorization to do otherwise (which currently is none!)

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
I wonder if there's a balance we should try to strike, maybe give unauthenticated users a max page size of 50 or 100, for example? That would still provide a 5x decrease from the current maximum. 

We can be almost certain that the `page_size=500` are doing so in an attempt to access the full dataset. ~100 still seems like the range that a non data-aggregating user might find useful.

**Comment by sarayourfriend** [comment]
I think considering our API is full open and to authenticate takes ~5 minutes of not-that-much effort (you can copy/paste the entire flow from the API's documentation website) it doesn't seem like a high bar to require for accessing bigger features.

**Comment by AetherUnbound** [comment]
100 per page still seems like a lot, especially when our default is 20. Since the Photo Directory and Openverse are distinct projects, I think it's okay to diverge here. Especially given that it's fairly easy to request an API key and get more results with a larger `page_size`.
