### ISSUE TITLE
Add individual command logging for index/constraint application step

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#752]
## Description

As part of the investigation around the API response time jumping dramatically during a data refresh, we identified that the index & constraint application step specifically was causing the API degradation. I suspect that there may be a single index/constraint application that is causing the slowness, rather than the entire set of `ALTER`s. In order to test this hypothesis, we need accurate logging for when each step is run.

Specifically, these two query executions should be split up into the individual alters, and each one should be logged when it is run:

https://github.com/WordPress/openverse-api/blob/5435e0e25d13c4b8b4e99ccaa7548a1e71f97683/ingestion_server/ingestion_server/ingest.py#L352

https://github.com/WordPress/openverse-api/blob/5435e0e25d13c4b8b4e99ccaa7548a1e71f97683/ingestion_server/ingestion_server/ingest.py#L359

## Additional context

Similar logging was added for the go-live step in #415

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
> Specifically, these two query executions should be split up into the individual alters, and each one should be logged when it is run:

Please log when it is run and when it finishes, maybe even log the delta if possible just so it's nice and easy to diagnose if there's an issue there :slightly_smiling_face:

**Comment by AetherUnbound** [comment]
Ah, they're run immediately after each other, so I was thinking the logs in CloudWatch would end up looking something like this:

```
2022-05-27 05:23:00,000 INFO ingest.py:356 - ALTER <column> ADD INDEX <foo>
2022-05-27 05:23:10,000 INFO ingest.py:356 - ALTER <column> ADD INDEX <bar>
2022-05-27 05:23:20,000 INFO ingest.py:356 - ALTER <column> ADD INDEX <baz>
2022-05-27 05:23:30,000 INFO ingest.py:356 - ALTER <column> ADD CONSTRAINT <zip>
```

Do you think that'd be sufficient? That would give us the exact indications of when each one starts, and since these are run serially the end can be assumed to just before the next line starts.

**Comment by sarayourfriend** [comment]
I guess for all except the last one?

**Comment by AetherUnbound** [comment]
These are the only steps run after before another log line appears:
https://github.com/WordPress/openverse-api/blob/5435e0e25d13c4b8b4e99ccaa7548a1e71f97683/ingestion_server/ingestion_server/ingest.py#L353-L356

`_update_progress` just sets a value:
https://github.com/WordPress/openverse-api/blob/5435e0e25d13c4b8b4e99ccaa7548a1e71f97683/ingestion_server/ingestion_server/ingest.py#L247-L249

I feel like that gives us a good enough time bounding. If anything though, I can swap the log line and the `_update_progress` one.
