### ISSUE TITLE
Remove CC-Catalog references in API docs diagram in readme

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-api#758]
## Description

> The API readme has references to CC-Catalog in the System Architecture diagram

Reported by @obulat 

We should re-create the diagram for Openverse. Use a tool that can export the diagram to XML or JSON or something so we can add it to the repository and easily update it again in the future.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
Hi @raghuvar-arora-au2! I'll assign the issue to you, thanks for picking this up 😄 

There are a couple of tools you can use for this, like [Lucidchart](https://www.lucidchart.com) or [Draw.io](https://draw.io). Alternatively, GitHub recently announced [Mermaid support in Markdown! 🧜🏼‍♀️](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) It would be very cool to try this out for this diagram, since we would be able to edit it like other Markdown files in our VCS 😄

**Comment by sarayourfriend** [comment]
Draw.io does indeed have an XML export option and also does not require an account to use (unlike the very locked down Lucidchart).

Mermaid is an interesting option, but I find it to be a lot more difficult and annoying to work with than a graphical tool, YMMV. Choose whatever you think is best from those options and thanks @raghuvar-arora-au2!

**Comment by raghuvar-arora-au2** [comment]
![image](https://user-images.githubusercontent.com/28990489/175575765-eba41246-d98a-4be7-b894-de88d8888ed0.png)
What should I put here or do I let it remain the same?

**Comment by raghuvar-arora-au2** [comment]
![image](https://user-images.githubusercontent.com/28990489/175576168-ec7fb322-5a15-42f7-af8c-3ff827b3024f.png)
What's happening in this part of the flow?

**Comment by sarayourfriend** [comment]
I think we can remove the proxy branch altogether now, but someone else from @WordPress/openverse-maintainers should confirm that.

**Comment by obulat** [comment]
> ![image](https://user-images.githubusercontent.com/28990489/175576168-ec7fb322-5a15-42f7-af8c-3ff827b3024f.png) What's happening in this part of the flow?

Ingestion server is the service that initializes the process of `ingestion`, when we get the data from the Catalog database into the database that is used by the API.

**Comment by raghuvar-arora-au2** [comment]
Thanks for clearing the confusion.
