### ISSUE TITLE
Sent API registration emails contained a typo

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#770]
We recently used a one-off script to send emails to users who had registered for the Openverse API during a time period in which verification emails were broken. Unfortunately, the emails we sent contained broken link with a url with two slashes, like so:

```
                      error here: ↓
https://api.openverse.engineering//v1/auth_tokens/verify/{mytoken}
```

We should most likely:

1. Reintroduce the one-off script (it was removed in this PR: https://github.com/WordPress/openverse-api/pull/768)
2. Fix the duplicated slash
3. **Bonus**: The emails were shown to be sent from 'noreply'; ideally we could set a name like 'Openverse API Team' or something in the code. Here's how it looked in Gmail:
  <img width="1209" alt="CleanShot 2022-06-24 at 12 42 30@2x" src="https://user-images.githubusercontent.com/6351754/175602876-aa9c78df-4143-4a26-adaf-7a647e357e50.png">

Edit: As @sarayourfriend indicated, we can identify the users we emailed in production under the `resendoauthverification:processed` redis key.

**Comment by aod-123** [comment]
@zackkrida Are the verification emails still broken? I was attempting to register earlier today and still have not received an email to verify?

**Comment by zackkrida** [comment]
As far as I'm aware the emails are working, @aod-123. I just tried to register myself and got the confirmation instantly, after running the following command:

```shell
curl \
  -X POST \
  -H "Content-Type: application/json" \
  -d '{"name": "My amazing project", "description": "To access Openverse API", "email": "user@example.com"}' \
  "https://api.openverse.engineering/v1/auth_tokens/register"
```

**Comment by aod-123** [comment]
@zackkrida The first email address I tried was for a Google Group/Bot (anything sent to the email address goes to each of our admins emails) and as far as our IT team could tell nothing seems to have come in for that address. I've tried another individual address our company has and it appears to work with that one though it did go to spam right away in GMail. I'm not sure if that would be the reasoning why it didn't come through for the group but I suppose just a heads up that companies with a similar setup may not get the verification email.

Sorry, just a follow up question as well, I noticed the expires_in value is for 10 hours. Does this mean we would need to have a CRON job or something setup to refresh our token every 10 hours? Is there a specific reason it's 10 hours and not 12? 

Thanks for your help!

**Comment by sarayourfriend** [comment]
Thanks for the extra information @aod-123, that's very helpful! As for the expiration: I'm not sure why it returns for 10 hours. Frankly, I don't see where in the code we actually assign a specific expiration to tokens. 10 hours does seem arbitrary :thinking:

**Comment by aod-123** [comment]
@sarayourfriend It could be a default value that's just coming through? Might there be any plans for having longer expiration times on the tokens? Or potentially changing it to at least every 12/24 hours or so instead of the 10? For now, I'll need to update our project to refetch a token (authenticate) every ten hours or when a 401 is received. We originally implemented when CC was handling the project and so just needed an API key with no expiry in the past, we didn't realize that our key had no longer been working until the recent change regarding limiting page results.

**Comment by sarayourfriend** [comment]
> Bonus: The emails were shown to be sent from 'noreply'; ideally we could set a name like 'Openverse API Team' or something in the code. Here's how it looked in Gmail:

For this part, we need to update the `DEFAULT_FROM_EMAIL` environment variable to follow the `NAME <EMAIL>` format: https://stackoverflow.com/a/2112818
