### ISSUE TITLE
Update the auth token expiry to be 12 or 24 hours

### ISSUE THREAD

**Issue by aod-123** [WordPress/openverse-api#773]
## Problem
Currently the token returned from the auth_tokens/token route returns a token that expires in 10 hours. To make this a little more consistent with typical CRON scheduling it would be more ideal for this expiry to be 12 or 24 hours.

## Description
Updating the auth token expires_in time would allow for more consistent CRON scheduling and most users would more typically expect it to expire every 12/24 hours.

## Alternatives
No suggestions aside from even longer expiry times (maybe once a year or once a month, etc).

## Additional context
Issue/suggestion originally came up here: [https://github.com/WordPress/openverse-api/issues/770](https://github.com/WordPress/openverse-api/issues/770)

## Implementation
- [ ] 🙋 I would be interested in implementing this feature.

**Comment by raghuvar-arora-au2** [comment]
Can I work on this?

**Comment by sarayourfriend** [comment]
Yes please @raghuvar-arora-au2! I've assigned the issue to you. Thank you!!
