### ISSUE TITLE
Identify fields to record for audio

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-api#82]
A lot of different providers provide different bits of information pertaining to audio. The goal is to identify a list of fields that we should record in every "audio" model such that:
- each quantum of required information gets a field of its own
- as few fields as possible go unpopulated or `NULL`

**References:**
- [API providers sheet](https://docs.google.com/spreadsheets/d/1uFj-oVJj64qGOydAtc3-o_suZIN_BL2ONlmBJzpe9-I/edit)

**Comment by krysal** [comment]
We discussed the fields for audio records this week in the [Openverse meeting](https://wordpress.slack.com/archives/C02012JB00N/p1623769149112600), so to summarize, I post the outcomes here; correct me if anything is wrong. @dhruvkb already did a great job creating the Django models for the API, so this is also based on that and should unlock several PRs for review and approval.

In addition to the [base model fields](https://github.com/WordPress/openverse-api/pull/79/files), audio records will have:

```
Audio
- duration (in milliseconds)
- bit_rate
- sample_rate
- type: if it is a song, podcast, audiobook, or sound effect (SFX).
- genre: Pop, Rock, Hip hop, Electronic, etc.
- audio_set: FK to the album, podcast series, or general audio collection.
- set_position
- meta_data:
    - year or date
    - description
    - instruments
    - every other insightful info APIs can provide
```

The `url` will be the highest quality audio file available (aiming for the 320kbps mp3 as the default), introducing this to alternatives versions of the same audio.

```
AltAudioFile
- url (from which the file_type/extension derives)
- filesize
- bit_rate
- sample_rate
```

And we'll add audio sets to save the info of collections as Album or Podcast series. This is a model with a different purpose of the AudioList.

```
AudioSet
- artist
- cover
- meta_data:
    - year
    - description
    - ...
```

Some notes:
- I'm inclined towards moving `genre` inside `meta_data`. It's only for music records.
- Thinking about filters for audio search, potentially, the fields used in a first iteration could be: the file type (.mp3, .wav, .ogg, ...), audio type (song, SFX, ...), duration range?
- About popularity-related metrics, my assumption is that the specifics of each provider (reproductions, downloads, likes, comments, rating, etc.) will remain in the catalog database, and the API database will store only the `standardized_popularity` that is updated periodically.

cc @obulat @zackkrida

**Comment by dhruvkb** [comment]
@krysal thanks for summarising the models here. 

I also wanted to offer some additional material that might be noteworthy.
- At the lowest level, genre can be assumed to be a secondary level of classification that can be applicable to all categories of audio. For example it can be applied to
  - podcasts: technology, politics etc.
  - audiobooks: fiction, self-help etc.
  
   We could delete it if the secondary classification level is not needed.
- Some of the filters that you are considering have been added in the [`AudioSearchQueryStringSerializer` serializer](https://github.com/WordPress/openverse-api/pull/105/files#r654625221) of PR #105.

**Comment by krysal** [comment]
Putting it that way, it makes sense to leave `genre` at a high level, and could also be a filter then.

**Comment by obulat** [comment]
Thank you for putting it all in writing, @krysal and @dhruvkb !

I think that `genre` should be a first-level field. However, we might want to make it a json field, because many audios might have several genres. For example, the first audio I get from jamendo has the following "genres" array: `["rock", "metal","hardcore"]`.

**Comment by zackkrida** [comment]
Noting that `type` has been renamed to `category` and `genre` is a top-level array field.

**Comment by zackkrida** [comment]
Fields have been identified 🥳
