### ISSUE TITLE
Fix docker generated file permissions

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-api#820]
## Description

When docker runs as root and creates files on a mounted volume, those files will have `root:root` permissions and will not be able to be modified or deleted by a regular user on the computer. See https://github.com/WordPress/openverse-api/runs/7526184802?check_suite_focus=true for example.

We can fix the permissions by running as a non-root user. See how this is done for the frontend: https://github.com/WordPress/openverse-frontend/blob/c4a117a11ddda2d0085506c88284db43e2784223/docker-compose.playwright.yml#L11

## Reproduction

Run the API via docker and then try to delete the files it creates as a normal user on your computer. It should fail similarly to in the GitHub action linked above.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
Rising to high priority🔺 because it's making our CI pipeline fail.
