### ISSUE TITLE
User-Agent setting needed for Wikimedia watermarked images

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-api#826]
## Sentry link

https://sentry.io/share/issue/699d8b5534e34b03a0dd721e32cbc7b9/

## Description

Wikimedia images requests fail at `v1/images/{identifier}/watermark/` endpoint due to Wikimedia's policies. Sentry shows:

> reason: Forbidden. Please comply with the User-Agent policy: https://meta.wikimedia.org/wiki/User-Agent_policy

So we cannot get the image in the API, and the below function fails; therefore, the request to the endpoint fails (500 error). Sentry shows that this is a new issue.

https://github.com/WordPress/openverse-api/blob/81b7860e2662f4b135919da0728eea194f15c260/api/catalog/api/utils/watermark.py#L140-L150

## Reproduction

See the error at https://api-dev.openverse.engineering/v1/images/f225be68-0b96-465e-8e04-836aae2c1419/watermark/

## Additional context

Related to #483.

**Comment by dhruvkb** [comment]
To be fair, watermarked is a deprecated (and to the best of my understanding, unused) API. If we could, I'd prefer to delete that code entirely instead of fixing and maintaining it.

**Comment by krysal** [comment]
Sounds fair, though I don't know if we can say it's unused given the number of occurrences of the event.

![CleanShot 2022-07-28 at 15 57 02@2x](https://user-images.githubusercontent.com/9145885/181626349-f9f72570-357e-459b-9522-0dec43f48f99.png)

And this error is only with Wikimedia, more people might be using this feature. @WordPress/openverse-maintainers what do you think?
