### ISSUE TITLE
`piexif.dump` errors are not safely handled

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-api#849]
## Sentry link

https://sentry.io/share/issue/a80d52de7f89436586ed0250cd0a32d2/

## Description

The call to `piexif.dump` should be wrapped in a `try/except` to prevent these errors in the watermark endpoint.

## Reproduction

Visit https://api-dev.openverse.engineering/v1/images/a913fde1-d524-4059-bd4f-9bd687578cc3/watermark/ to see an example of this failure.

**Comment by AetherUnbound** [comment]
Closing this in favor of #827, as both Sentry errors are manifestations of the same issue. I'll also merge the Sentry issues together.

**Comment by krysal** [comment]
We're not catching all the exceptions on this code block so reopening.

https://github.com/WordPress/openverse-api/blob/6b7e963419d4894260934046c5421f9b932de743/api/catalog/api/utils/watermark.py#L157-L170
