### ISSUE TITLE
Only fill in pages if at least one link from first page is not dead

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-api#855]
## Problem

If we make a request to ES for 20 items and find that any of them are dead, we attempt to "fill the page in" with subsequent "deeper page" queries. If _all_ the links for a query are dead, this means we will slam ES with tons of fast queries to try to fill in the page.

## Description

Kudos @obulat for the idea. We should not try to fill pages if all of the links on the first page are dead.

## Additional context
We are also working on excluding providers that account for a large number of dead links.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
Some relevant discussion here: https://github.com/cc-archive/cccatalog-api/issues/565
