### ISSUE TITLE
Rename `validate_images` to `validate_media`

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#885]
## Description

The [`validate_images` function/module](https://github.com/WordPress/openverse-api/blob/a26784eddccedafcbfb1f4aa250f22abedd2f1db/api/catalog/api/utils/validate_images.py) is actually used to verify audio results as well as images. This can make the logs confusing, as audio results will show up with logs such as `Image validation failed due to <x>`.

We should rename both the module and the function to better reflect this behavior.

## Additional context

See #884 for the original context

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
I think this is more or less a duplicate of https://github.com/WordPress/openverse-api/issues/725, isn't it?

**Comment by AetherUnbound** [comment]
Oops, it is, thanks Sara! Closing this in favor of #725.
