### ISSUE TITLE
Switch to `MoreLikeThis` class in the search controller

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-api#915]
I noticed that instead of specifying the query type as a string in the earch controller, we can instead import the [`MoreLikeThis` query type](https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#more-like-this-query) directly for the related image query.

https://github.com/WordPress/openverse-api/blob/a6c959b119f49ce06855293b9f863d776d907a2e/api/catalog/api/controllers/search_controller.py#L424

**Comment by Akshat977** [comment]
Hi @zackkrida  ,
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by zackkrida** [comment]
Sure @Akshat977!

**Comment by ritesh-pandey** [comment]
@Akshat977 Are you still working on this?
