### ISSUE TITLE
Broken link to image landing page in Django admin

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse-api#935]
## Description

The functionality for reporting media works fine. But on the API side, there are a lot of parts that are broken and out of date.

- The base URL for reported media items still points to CC.
  https://github.com/WordPress/openverse-api/blob/32189d05db91f8a7587c48017f910bfa9718c6bd/api/catalog/api/models/media.py#L136

- The `ImageReport` model thinks that images are hosted at `/photos`.
  https://github.com/WordPress/openverse-api/blob/32189d05db91f8a7587c48017f910bfa9718c6bd/api/catalog/api/models/image.py#L58

If I find any more before the issue is picked up, I'll add them here.

## Additional context

To the best of my knowledge, submitting reports works. These problems only affect those who are looking into the submitted reports.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by swapnalshahil** [comment]
@dhruvkb where should the base URL for the reported media point?
