### ISSUE TITLE
Replace the old CC `BASE_URL` of media reports

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse-api#965]
## Description

Currently, the media reports appear in the Django Admin with a URL from Creative Commons, meaning that when you click on the link it will count as a referrer from the old CC Search site, which is not true. The `BASE_URL` should be `https://wordpress.org/openverse/`.

This can be fixed by editing the following line.

https://github.com/WordPress/openverse-api/blob/21405cc4a4ea2f8dca41559d9e5e29763b188e86/api/catalog/api/models/media.py#L145

And potentially and preferably we can centralize this constant in the `settings.py` file for the example responses as well.

https://github.com/WordPress/openverse-api/blob/21405cc4a4ea2f8dca41559d9e5e29763b188e86/api/catalog/api/examples/audio_responses.py#L4

https://github.com/WordPress/openverse-api/blob/21405cc4a4ea2f8dca41559d9e5e29763b188e86/api/catalog/api/examples/image_responses.py#L4

## Reproduction

1. Run `just up` to bring up the API
2. Pick any id from http://localhost:50280/v1/audio/ (or from the image list)
3. Replace `<uuid>` with the id previously selected and create a media report with:
```sh
curl -X POST \
	-H 'Content-Type: application/json' \
	-d '{
		"mediaType":"audio",
		"identifier":"<uuid>",
		"reason":"other",
		"description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse blandit id felis sed imperdiet. Integer tristique nisi et metus sollicitudin."
	}'\
	http://localhost:50280/v1/audio/<uuid>/report/
```
4. Go to http://localhost:50280/admin/api/audioreport/ The user & pass for the local API is `deploy`
5. See the wrong URL under the "Audio url" column.

## Screenshots

![CleanShot 2022-10-03 at 12 41 28@2x](https://user-images.githubusercontent.com/9145885/193637806-7791a22f-86c0-4004-a51a-84252075c43d.png)

**Comment by swapnalshahil** [comment]
Hi @krysal BASE_URL should be replaced by which URL? Clicking on the BASE_URL appears as a referrer `https://wordpress.org/openverse/?referrer=creativecommons.org` here.

**Comment by krysal** [comment]
@swapnalshahil That's correct! Sorry I forgot to mention the new URL, https://wordpress.org/openverse/ is indeed the new home of Openverse 😄 Do you want to try to solve this issue? I can assign it to you.

**Comment by swapnalshahil** [comment]
@krysal Yes!
