### ISSUE TITLE
Remove SourceLogo class

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse-api#986]
## Problem

It doesn't appear that we use this data in production... I checked a handful of providers (including big ones like Wikimedia and other smaller ones) and none had an image uploaded. Currently, the uploaded SourceLogo objects get stored directly on disk and get wiped out on each deployment :scream: That leads me further to believe that these are not used or depended on by anyone, as they do not appear to work correctly in production (at least not to my naive expectations of these, that they would persist across deployments) and our current setup doesn't accommodate them at all.

## Description

Can we remove this functionality? Has it ever been used in production/what was the intended use case for it (aside from providing a source logo URL along with the individual provider metadata)?

Removing it would simplify the Django API infrastructure in that it would allow us to avoid needing to map any volumes between the Nginx and Django containers once #821 is completed.

Plus, if we can avoid needing to handle uploads (and backing them up!) then that would be great as well.
## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
Oh, that's a great find Krystle! I could also imagine that we might just store a URL to a logo if we wanted this in the future, rather than storing the URLs ourselves 😮 Either way, I think we'd be clear to remove it 🙂
