### ISSUE TITLE
Link for automated tests file broken in DOCUMENTATION_GUIDELINES.md

### ISSUE THREAD

**Issue by Yash-Pratapwar** [WordPress/openverse-api#992]
## Description
I clicked the [link](https://github.com/WordPress/openverse-api/blob/main/DOCUMENTATION_GUIDELINES.md#:~:text=Make%20sure%20the%20updates%20passed%20the%20automated%20tests%20in%20this%20file) for` automated tests file` in `DOCUMENTATION_GUIDELINES.md` and instead of going to the appropriate location is says `The 'WordPress/openverse-api' repository doesn't contain the '.github/workflows/integration-tests.yml' path in 'main'.`  I think the location of the file has been changed, If anyone could tell me the correct location I will be able to resolve this error.

## Reproduction

1. Go to [DOCUMENTATION_GUIDELINES.md](https://github.com/WordPress/openverse-api/blob/main/DOCUMENTATION_GUIDELINES.md#documentation-guidelines)
2. Navigate to [How to Start Contributing](https://github.com/WordPress/openverse-api/blob/main/DOCUMENTATION_GUIDELINES.md#how-to-start-contributing)
3. Click on the [link](https://github.com/WordPress/openverse-api/blob/main/.github/workflows/integration-tests.yml) in the 3rd point under [How to Start Contributing](https://github.com/WordPress/openverse-api/blob/main/DOCUMENTATION_GUIDELINES.md#how-to-start-contributing)
4. See error.

## Screenshots
![image](https://user-images.githubusercontent.com/65851650/198838539-fef8fe43-0453-4618-a772-7cce7310b185.png)

## Environment

 - Device: Laptop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 106.0.5249.119

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
Great find! This should probably link to our CI/CD file instead now: https://github.com/WordPress/openverse-api/blob/main/.github/workflows/ci_cd.yml

**Comment by Yash-Pratapwar** [comment]
> Great find! This should probably link to our CI/CD file instead now: https://github.com/WordPress/openverse-api/blob/main/.github/workflows/ci_cd.yml

@AetherUnbound I will start working on it thanks!

**Comment by Yash-Pratapwar** [comment]
@AetherUnbound I had one question about the contribution process, do I need to set-up anything or should I directly fork > create a new branch > do the changes > push it > create a PR?

**Comment by AetherUnbound** [comment]
That's correct! You can see this from [step 7 on in our contributing guide](https://github.com/WordPress/openverse/blob/0b5e24bd325da7b75db9484a268d7c8d197ae920/CONTRIBUTING.md#%EF%B8%8F-general-set-up). You should only need to fork the repo once, but every new PR will require a new branch.

**Comment by Yash-Pratapwar** [comment]
Thanks! Will follow these instructions.

**Comment by Yash-Pratapwar** [comment]
@AetherUnbound where can I find the instructions to set up the environment?

**Comment by AetherUnbound** [comment]
Hi @Yash-Pratapwar, please see the contributing guide for this repo: https://github.com/WordPress/openverse-api/blob/main/CONTRIBUTING.md. That document does need some updating for use with our command runner `just`, I'll make an issue for it.

**Comment by AetherUnbound** [comment]
Ah, I found it 😄 #973 - and you've also offered to help there as well!

**Comment by Yash-Pratapwar** [comment]
Thanks, I will go through it 👍🏽
